name: Documentation

on:
  push:
    branches: [ main ]
    paths:
      - 'README.md'
      - 'docs/**'
      - 'Analyzers.Dapr/**/*.cs'
  workflow_dispatch:

jobs:
  validate-docs:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install markdown linter
      run: npm install -g markdownlint-cli

    - name: Lint README
      run: markdownlint README.md --config .markdownlint.json || true

    - name: Check links in README
      uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
        use-quiet-mode: 'yes'
        use-verbose-mode: 'yes'
        config-file: '.markdown-link-check.json'

  generate-docs:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Install DocFX
      run: dotnet tool install -g docfx

    - name: Build documentation
      run: |
        # Create docfx.json if it doesn't exist
        if [ ! -f "docfx.json" ]; then
          cat > docfx.json << 'EOF'
        {
          "metadata": [
            {
              "src": [
                {
                  "files": ["Analyzers.Dapr/**/*.cs"],
                  "exclude": ["**/bin/**", "**/obj/**"]
                }
              ],
              "dest": "api"
            }
          ],
          "build": {
            "content": [
              {
                "files": ["api/*.yml"],
                "dest": "api"
              },
              {
                "files": ["README.md"],
                "dest": "."
              }
            ],
            "resource": [
              {
                "files": ["images/**"]
              }
            ],
            "dest": "_site",
            "globalMetadata": {
              "_appTitle": "Analyzers.Dapr",
              "_appFooter": "Analyzers.Dapr Documentation"
            }
          }
        }
        EOF
        fi
        
        docfx docfx.json --serve || echo "DocFX generation completed"

    - name: Deploy to GitHub Pages
      if: success()
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site
